### ISSUE TITLE
make test failed

### ISSUE THREAD

**Issue by CarlaRomano** [lanl/LaGriT#193]
Hi
I am trying to install LaGriT for using it with dfnWorks. I followed your instructions with exodus build. Everything is fine until I run the make test. 
It gives me: All checks complete, 2 directories failed out of 41
Makefile:198: recipe for target 'test' failed
make: *** [test] Error 1 

I have checked in the terminal (not sure if I have a log file for this test) and it appears to me that there are two main issues:
"Lines Essentially the Same: 2 out of 220
Test has 496 diffs at line 237 >>
Test has 484 extra lines in this chunk.
Lines Essentially the Same: 496 out of 496
2637 lines failed." 
This is before step "9 Done with Directory ./quality".

The second issue is "22 Check Directory ./cmo_addatt_normals --------------------------
Test has 3 diffs at line 259 >>
Test has 3 extra lines in this chunk.
Lines Essentially the Same: 3 out of 3
Test has 3 diffs at line 330 >>
Test has 3 extra lines in this chunk.
Lines Essentially the Same: 3 out of 3
6 lines failed."

Any idea of what I am doing wrong?
Thank you so much

**Comment by daniellivingston** [comment]
Hi @CarlaRomano , thanks for your interest in LaGriT. This is a known issue; your build is fine and I will resolve this sometime within the next few days.

The way our regression tests are configured is: each test is a simple LaGriT demo characterizing critical subroutines and workflows. The test is run and stdout is piped to a file; this file is compared to a 'gold standard' file. If the files differ (i.e., because mesh quality is different or errors/warnings are thrown), then the test fails.

Some algorithms were recently changed and their output differs from what the test case expects. The test cases haven't been updated to reflect that yet.

Related: #185

**Comment by daniellivingston** [comment]
Also, if you are interested, we have a Docker container with dfnWorks and all pre-built dependencies here: https://hub.docker.com/r/ees16/dfnworks

If you have Docker installed already, this might be the easier way to go.

**Comment by millerta** [comment]
Note the quality command has output that differs from pre-2019 versions. The quality reports involving normalized values is fixed and includes a message with words "normalized by dividing" to clarify how values are normalized.

**Comment by millerta** [comment]
Test suite has been updated to current master. There should be no failures from level01 tests.

**Comment by CarlaRomano** [comment]
Thanks you all. Everything works well.
