### ISSUE TITLE
add test for createpts, filter, filterkd

### ISSUE THREAD

**Issue by millerta** [lanl/LaGriT#59]
This is a nice test for the filter command, add to test01
But first evaluate results with Carl Gable so we are confident in the files saved to /reference

define / SIZE / 0.01
define / EPS1 / 0.01
define / EPS2 / 0.02
define / EPS3 / 0.03
define / EPS4 / 0.04
 
cmo / create / mo1
createpts/random / xyz / SIZE / 0 0 0 / 1 1 1 / , , / / 1
createpts/random / xyz / SIZE / 0 0 0 / 1 1 1 / , , / / 2
createpts/random / xyz / SIZE / 0 0 0 / 1 1 1 / , , / / 3
filter / 1 0 0 ; rmpoint / compress
filter / 1 0 0 / EPS1 ; rmpoint / compress
filter / 1 0 0 / EPS2 ; rmpoint / compress
filter / 1 0 0 / EPS3 ; rmpoint / compress
filter / 1 0 0 / EPS4 ; rmpoint / compress
 
 
 
cmo / create / mo2
createpts/random / xyz / SIZE / 0 0 0 / 1 1 1 / , , / / 1
createpts/random / xyz / SIZE / 0 0 0 / 1 1 1 / , , / / 2
createpts/random / xyz / SIZE / 0 0 0 / 1 1 1 / , , / / 3
filterkd / 1 0 0 ; rmpoint / compress
filterkd / 1 0 0 / EPS1 ; rmpoint / compress
filterkd / 1 0 0 / EPS2 ; rmpoint / compress
filterkd / 1 0 0 / EPS3 ; rmpoint / compress
filterkd / 1 0 0 / EPS4 ; rmpoint / compress
 
finish

**Comment by daniellivingston** [comment]
Tests have been created and uploaded to the repo (createpts_filter/ & triangulate_polygon/). Need to verify output in outx3dgen with @cwgable.

**Comment by daniellivingston** [comment]
Upon talking with Carl, output from `filter` and `filterkd` show a high discrepancy in the final number of final filtered points, when they should be approximately the same. Reopened.

**Comment by cwgable** [comment]
Some updates to the documentation should be done to document filterkd.

**Comment by daniellivingston** [comment]
Fixed in commit [`b5e6644`](https://github.com/lanl/LaGriT/commit/b5e66444775a9dc744e55c8c19eb68c680b192e7).

The test case in `tests/level01/createpts_filter`, made with @cwgable, was created to illustrate the differences between `filter` and `filterkd`. Two unit cubes are created, one with 10^6 evenly spaced points, and another with 10^6 points slightly perturbed around their cells. The perturbed cube is appended to the regularly spaced cube. Each set of points is given a different imt value. In an ideal case, the perturbed points would be removed, leaving exactly 10^6 points with imt=1.

What is found is that `filter`, which uses a binning method for point removal, targets points more stochastically and removes 48.6% of them, leaving behind both perturbed and regular points.

`filterkd`, which is based on a [`kd-tree`](https://en.wikipedia.org/wiki/K-d_tree) method, removes every perturbed point and leaves behind every regular-spaced point.
