### ISSUE TITLE
Failed to build LaGriT on Windows

### ISSUE THREAD

**Issue by TangLaoya** [lanl/LaGriT#92]
Dear all,
I tried to build the LaGriT on Windows. I tried to built static library but when I link the library to execuatable file, the following errors displayed:
Error	1	 error LNK2019: unresolved external symbol inside_tet_ referenced in function computescalarVoronoientry	LaGriT_C.lib(anothermatbld3d.obj)	
Error	2	 error LNK2019: unresolved external symbol lineseg_tri_ referenced in function intersectSegmentWithFace	LaGriT_C.lib(anothermatbld3d.obj)	

I searched these two functions in the whole folder and didn't find them, could anyone tell me where these two functions are defined?

Thanks,
Tang Laoya

**Comment by daniellivingston** [comment]
Both are defined in `LaGriT/src/anothermatbld3d.c`.

To help you debug, can you tell me the terminal (Cygwin, cmder, etc.) and shell (bash, csh, etc.) that you are using?

**Comment by daniellivingston** [comment]
You can also find a Windows executable here: https://github.com/lanl/LaGriT/releases/tag/V3.3

I believe that this won't work unless you execute it in a bash shell, like Cygwin.

**Comment by TangLaoya** [comment]
Dear daniellivingston,
Thank you very much for your kindly reply. 
Yes, both functions are defined in anothermatbld3d.c:
/* Declare some Fortran functions we're going to use so that the compiler can do
 * type checking. */
void inside_tet_(
        double *x1, double *y1, double *z1,
        double *x2, double *y2, double *z2,
        double *x3, double *y3, double *z3,
        double *x4, double *y4, double *z4,
        double *xa, double *ya, double *za,
        int_ptrsize *flag);

void lineseg_tri_(
        double *x1, double *y1, double *z1,
        double *x2, double *y2, double *z2,
        double *x3, double *y3, double *z3,
        double *xa, double *ya, double *za,
        double *xb, double *yb, double *zb,
        double *x, double *y, double *z,
        int_ptrsize *flag);

but there are only definition, no further execute code. 

Thanks,
Tang Laoya

**Comment by TangLaoya** [comment]
In fact, currently I can build the code into executable file by commenting out these lines:
        inside_tet_(&Mesh->xic[v1],&Mesh->yic[v1],&Mesh->zic[v1],
                     &Mesh->xic[v2],&Mesh->yic[v2],&Mesh->zic[v2],
                     &Mesh->xic[k1],&Mesh->yic[k1],&Mesh->zic[k1],
                     &Mesh->xic[k2],&Mesh->yic[k2],&Mesh->zic[k2],
                     &tetCenterx, &tetCentery, &tetCenterz, &flag);
        if (flag == -1 && getHybridPoint(incidentTets[tetIndex] - 1,
                    tetCenterx, tetCentery, tetCenterz,
                    &xhybrid, &yhybrid, &zhybrid,
                    &Mesh->hybrid_factor[incidentTets[tetIndex] - 1])) {
            tetCenterx = xhybrid;
            tetCentery = yhybrid;
            tetCenterz = zhybrid;
        }

because in the code you also said:
        /* This call might not be necessary. getHybridPoint will find out later
         * whether or not the circumcenter is inside the tet. */

Thanks,
Tang Laoya

**Comment by daniellivingston** [comment]
Huh, that's interesting...you might run into issues if you try to run functions like `dump/stor` for a 3D mesh, or `cmo/addatt/vor_volume`.

The above `inside_tet_` and `lineseg_tri_` definitions in the C code actually call `inside_tet` from [src/inside_lg.f](https://github.com/lanl/LaGriT/blob/92a0cb1f317507341281378a0cd442aef3d21fab/src/inside_lg.f) and `lineseg_tri` from [src/linesegtri.f](https://github.com/lanl/LaGriT/blob/92a0cb1f317507341281378a0cd442aef3d21fab/src/linesegtri.f).

**Comment by TangLaoya** [comment]
Dear daniellivingston,
Thank you very much for your kindly reply. I see. So I have many work to do if I try to  build and debug LaGriT in Windows + IVF environment, for example, I have to provide many interfaces in Fortran code to let the data be passed between Fortran and C code:
https://software.intel.com/en-us/forums/intel-visual-fortran-compiler-for-windows/topic/753663

To build the LaGriT in Cygwin is a good method to build in Windows system, but it is very difficult to debug.

Thanks,
Tang Laoya

**Comment by daniellivingston** [comment]
For the Windows environment, we have had success building using gcc as the compiler and Cygwin as the terminal. This is all we can verify on the Windows side, currently.

In another Issue you wrote:

> I have put all Fortran source code in LaGriT-master\lg_util\src and LaGriT-master\src into one project

The files in `lg_util/` are built as a library first, which the files in `src/` then reference on compilation. The two directories are compiled independently, and compiling them both at the same time, which it sounds like you're doing, is probably going to give you issues. Both directories have their own Makefiles, which should be used for compilation, and you may be overwriting them (or, not even using them).

Regarding your Intel forum post, you should not need to modify the source code for it to build.

### This is what I would recommend: ###

There is a hard way and an easy way to build LaGriT. While your choice in using IVF might seem like the easy way, since it's an IDE, it is actually giving you many more problems than it should, since LaGriT was not built and not tested for your particular setup.

1. The *very* easy way: download Cygwin. Make sure, when it prompts you for tools to install, you check: `gcc`,`make`,`cmake`, `wget`, and `gfortran`.
Open Cygwin and run these lines:

``` sh
wget -O LaGriT https://github.com/lanl/LaGriT/releases/download/V3.3/LaGriT_V3.3_Windows-Cygwin.exe
chmod a+rwx LaGriT
./LaGriT
```

And now you're running LaGriT. Easy!

2. Download Cygwin (and check the same tools listed in step 1) and run:

``` sh
git clone https://github.com/lanl/LaGriT.git
cd LaGriT/
./install.sh --skipexodus
```

And now you have LaGriT. If you go down this route and have issues,  copy and paste the output it prints and we can help you much easier.

3. (Not recommended) Keep trying to build using IVF.

First: start over. Get a fresh clone of the LaGriT repo.
Second: if you are intent on using IVF instead of a terminal, don't modify the source code. Instead, modify your project *flags* and *settings*. The code is fine, with the appropriate compiler settings.
Model your flags and settings after [this](https://github.com/lanl/LaGriT/blob/master/lg_util/src/Makefile), [this](https://github.com/lanl/LaGriT/blob/master/src/Makefile) (for building `src/`), and [this](https://github.com/lanl/LaGriT/blob/master/documentation/INSTALL.md).

**Comment by TangLaoya** [comment]
Dear daniellivingston,
Thank you very much for your kindly suggestion. I would like to build LaGriT by IVF since it is very easy to debug code under Visual Studio IDE + Intel Visual Fortran. I will try to study and understand your 3rd suggestion.

Thanks,
Tang Laoya

**Comment by TangLaoya** [comment]
Dear daniellivingston,
I am sorry to bother you again. I noticed that you have told me to work on 3-D mesh by dump/stor or cmo/addatt/vor, but I still don't understand. Could you please give me more detailed information? For example, if I have built the executable file 'lagrit.exe' in Windows system, what command line should I run to let the lagrit.exe generate 3-D tet/hex mesh for the given domains specified by input files (examples in LaGriT-master\test)?

Thanks,
Tang Laoya

**Comment by daniellivingston** [comment]
Hi Tang,
Since we're getting off-topic from the main Issue thread, can you send me an email with this question to livingston@lanl.gov ?
