### ISSUE TITLE
What lead to this error message?

### ISSUE THREAD

**Issue by TangLaoya** [lanl/LaGriT#94]
Dear all,
I tried to run the simple example in test\level01\addmesh_add by Windows version of LaGriT. The command line to run the example is as follows:
LaGrit <input.lgi >out.txt

The errors are outputted into out.txt, could anyone help me to take a look at this problem?

Thanks,
Tang Laoya
[out.txt](https://github.com/lanl/LaGriT/files/1599637/out.txt)

**Comment by daniellivingston** [comment]
Tang,

It looks like this may be related to a size issue. On our Cygwin build, running `mmprint`, a command to output memory diagnostics, gives:

```
MEMORY SIZES : 
 Sizeof char    (type 3) =  1 bytes      Sizeof long        =   8 bytes
 Sizeof real*8  (type 2) =  8 bytes      Sizeof pointer     =   8 bytes
 Sizeof integer (type 1) =  4 bytes      Sizeof INT_PTRSIZE =   8 bytes
```

Note that your `long` has been compiled to be set to 4 bytes when it should be 8.
Memory management is done through the library built from the files in `lg_util/src/`.  If you are using the Makefile in that directory, ensure that this is set:

    #define SIZEOF_LONG 8

Otherwise, ensure your compiler settings and flags are configured correctly.

**Comment by TangLaoya** [comment]
Dear daniellivingston,
Thank you very much for your kindly reply. I have modifed pointer related variables in 'mm2000.h' to integer*8:

      pointer (adaptr, ad_addr)
      integer*8::ad_addr(AD_SIZE, *) !pointer - sized integer

      pointer (lptr, link)
      integer*8::link(*)

      integer*8::max_ad, num_ad, first, next
      common /mm2000/ max_ad, num_ad, first, next, adnptr, adaptr, lptr

but there are still these errors. Could you please help me to take a look at it?

Thanks,
Tang Laoya

**Comment by TangLaoya** [comment]
I also noticed that all related .h file include the following:

#ifdef win64
#define FCV_UNDERSCORE
#define SIZEOF_INT 4
#define SIZEOF_LONG 8
#define SIZEOF_VOIDP 8
#define MAX_UINT 18446744073709551615.00
#endif

I have set the preprocessor win64 in my compiling option. So what could lead to this problem?

In addition, I tried to modify code in mm2000.F->subroutine mmgetblk 
      integer prolog(*), epilog(*)
to 
      integer*8 prolog(*), epilog(*)

The errors happened ahead of that without this line modification. I have also attached the log file. Could you please help me to take a look at it?

Thanks,
Tang Laoya
[out.txt](https://github.com/lanl/LaGriT/files/1602365/out.txt)

**Comment by millerta** [comment]
You should not be changing code, that will break things.

Your error is a least in part due to your compile line not having the correct flags which will adjust sizes for all the code.

See the Makefile in each directory LaGriT/src and LaGriT/lg_util/src
When you compile each library there should be flags for windows compile that include something like:

     -fdefault-integer-8 -m64 -Dwin64

Each Makefile sets up the flags for your system, your execution of the Makefile may not be picking up your correct machine and flags.

Daniel can help with specifics since he has compiled on Windows (using Cygwin).

Can you email Daniel directly on this? "Livingston, Daniel Reece" <livingston@lanl.gov<mailto:livingston@lanl.gov>>


Terry A. Miller
Mesh Generation and Software
Computational Earth Science EES-16
tamiller@lanl.gov<mailto:tamiller@lanl.gov>
505-667-8009




On Jan 3, 2018, at 7:14 PM, TangLaoya <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear daniellivingston,
Thank you very much for your kindly reply. I have modifed pointer related variables in 'mm2000.h' to integer*8:

  pointer (adaptr, ad_addr)
  integer*8::ad_addr(AD_SIZE, *) !pointer - sized integer

  pointer (lptr, link)
  integer*8::link(*)

  integer*8::max_ad, num_ad, first, next
  common /mm2000/ max_ad, num_ad, first, next, adnptr, adaptr, lptr


but there are still these errors. Could you please help me to take a look at it?

Thanks,
Tang Laoya

**Comment by TangLaoya** [comment]
Thanks. The problem is solved by setting default integer as integer*8.
