### ISSUE TITLE
LaGriT crashed at 'delaunay'

### ISSUE THREAD

**Issue by TangLaoya** [lanl/LaGriT#96]
Dear all,
For the example in 'test\addmesh_add', I continued to test and found that it crashed at 'delaunay' here: 
        **do ii=1,nlstnew
            itetnoo=shiftr(ifacnew(ii)+3,2)
            iposo=iand((ifacnew(ii)+3),3)+1
            jtetnew(1,ii)=-1
            jtetnew(2,ii)=-1
            jtetnew(3,ii)=-1
            jtetnew(4,ii)=-1
            jtetnew(iposo,ii)=cvmgt(jtet(iposo,itetnoo),
     $                              jtet(iposo,itetnoo)-mbndry,
     $                              jtet(iposo,itetnoo).lt.mbndry
     $                             )
            jtet1(jtetnew(iposo,ii))
     $       =cvmgt(jtet1(jtetnew(iposo,ii)),4*(ntets+ii-1)+iposo,
     $              jtetnew(iposo,ii).le.0)            ! crashed at this line
         enddo**

I noticed that 'itet' is set to mbndry in function 'make_big_tet', and in the do loop, the jtetnew(iposo,ii) is set to 0 because jtet(iposo,itetnoo) = mbndry, but jtetnew(iposo,ii) is used as the subscript of array jtet1.

Could anyone help me to take a look at it?

Thanks,
Tang Laoya

**Comment by millerta** [comment]
There should be no problem with the code if you are using input files from the test directories.
If it is something to do with your machine and memory sizes it will be harder to help you
since we do not normally support or use LaGriT on Windows machines.

Can you send the input file and the outx3dgen file so we might help you figure out if
this is an error from running on Windows, or something in your command syntax.

Please email tamiller@lanl.gov<mailto:tamiller@lanl.gov> and livingston@lanl.gov<mailto:livingston@lanl.gov>

Terry A. Miller
Mesh Generation and Software
Computational Earth Science EES-16
tamiller@lanl.gov<mailto:tamiller@lanl.gov>
505-667-8009




On Jan 9, 2018, at 12:11 AM, TangLaoya <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear all,
For the example in 'test\addmesh_add', I continued to test and found that it crashed at 'delaunay' here:
do ii=1,nlstnew
itetnoo=shiftr(ifacnew(ii)+3,2)
iposo=iand((ifacnew(ii)+3),3)+1
jtetnew(1,ii)=-1
jtetnew(2,ii)=-1
jtetnew(3,ii)=-1
jtetnew(4,ii)=-1
jtetnew(iposo,ii)=cvmgt(jtet(iposo,itetnoo),
$ jtet(iposo,itetnoo)-mbndry,
$ jtet(iposo,itetnoo).lt.mbndry
$ )
jtet1(jtetnew(iposo,ii))
$ =cvmgt(jtet1(jtetnew(iposo,ii)),4(ntets+ii-1)+iposo,
$ jtetnew(iposo,ii).le.0) ! crashed at this line
enddo*

I noticed that 'itet' is set to mbndry in function 'make_big_tet', and in the do loop, the jtetnew(iposo,ii) is set to 0 because jtet(iposo,itetnoo) = mbndry, but jtetnew(iposo,ii) is used as the subscript of array jtet1.

Could anyone help me to take a look at it?

Thanks,
Tang Laoya

**Comment by TangLaoya** [comment]
Dear Miller,
I have sent emails to you, could you please help me to take a look at it?

Thanks,
Tang Laoya

**Comment by TangLaoya** [comment]
Dear Miller,
I checked the code again and found that before the crash point, the 'jtet' was assigned to 'mbndry' in the function 'make_big_tet' and it is not changed any more. Is there anyting wrong?

Thanks,
Tang Laoya

**Comment by TangLaoya** [comment]
Dear all,
I have tested all examples level01~level03 in test folder. There are more than half of examples didn't pass the test because of this crash (for 2d the crash point is similar to the 3d case). Could anyone help me to take a look at this problem? Could anyone try to run the sample case in Linux and show me the value of related variables when running to this line?

jtet1(jtetnew(iposo,ii)) $ =cvmgt(jtet1(jtetnew(iposo,ii)),4(ntets+ii-1)+iposo, $ jtetnew(iposo,ii).le.0) 

Thanks,
Tang Laoya

**Comment by daniellivingston** [comment]
Tang, 

We'd like to help you, but the issues with code modification and so forth extend far past codebase problems and thus GitHub Issues. So that we can help you debug the problems that you are having in more detail, please send an email (not a GitHub comment) to tamiller@lanl.gov and livingston@lanl.gov .

Thanks!

**Comment by TangLaoya** [comment]
Dear daniellivingston,
Thank you very much for your kindly reply. However, I have sent several emails to the two emails you listed but didn't receive any response. I don't know whether you have received my emails. My email address is 20959284@qq.com. 

Thanks,
Tang Laoya
