### ISSUE TITLE
Question in 'setbit.f'

### ISSUE THREAD

**Issue by TangLaoya** [lanl/LaGriT#97]
Dear all,
I noticed that in 'setbit', the 'imask' is defined as integer instead of integer array, however, in latter usage, 'imask' is used as an array:

      imask(idum)=2**(idum-1)
...
      maskv2=imask(j)

Is there any problem?

Thanks,
Tang Laoya

**Comment by millerta** [comment]
This part of the code is is using an integer (or array of integers) to access bit values from 0 to nbitnum.

I do not know much about this part of the code as it was written in the 1990's and has not changed since then.
If there is an error, we should fix it. But nothing has shown up in all our testing or usage over the years.

If you make a change, make sure you run the test suites to make sure nothing is broken.

Terry


On Jan 11, 2018, at 8:31 PM, TangLaoya <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear all,
I noticed that in 'setbit', the 'imask' is defined as integer instead of integer array, however, in latter usage, 'imask' is used as an array:

  imask(idum)=2**(idum-1)


...
maskv2=imask(j)

Is there any problem?

Thanks,
Tang Laoya

**Comment by TangLaoya** [comment]
Dear Terry,
Thank you very much for your kindly reply. I set breakpoints on related lines and test the example and found that they are not executed at all. I don't know whether this function is used in any other example.

Thanks,
Tang Laoya
